version: "3.7"

services:
  # Second Service
  # postgres
  db:
    environment:
      # POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: smart-brain2
    build: ./postgres
    ports:
      - "6000:5432"
  #redis
  redis:
    image: 'redis'
    ports:
      - "6379:6379"

  # backend API
  smart-brain-api:
    container_name: backend
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_URI: postgres://postgres:abcd@db:5432/smart-brain2
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: smart-brain2
      REDIS_URI: redis
    links:
      - db
      - redis
    build: ./
    command: npm start
    working_dir: /meisam/smartbrainapi
    ports:
      - "3000:3000"
    volumes:
      - ./:/meisam/smartbrainapi
